# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 일하는중,원중
title: 풀스택 개발자
email: gimpo5975@naver.com
phone: 010-9313-5975
website: https://github.com/gimpo5975

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  gimpo5975

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url: https://velog.io/@gehwan96

# About Section
about_title: 자기소개
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
    안녕하세요. <mark>풀스택개발자</mark> 원중의 블로그입니다😸 찾아주셔서 감사합니다!🙌🙌
    저에 대해서는 차차 작성예정입니다요.

content:
  - title: 프로젝트
    layout: list
    content:
      - layout: left
        title: MYSHOP
        link: https://github.com/gimpo5975/MyShop-practice.git
        link_text: MYSHOP 접속하기👈
        description: | # this will include new lines to allow paragraphs
          기존에 존재하는 쇼핑몰을 마킹해서 연습용으로 제작한 "MYSHOP"이라는 쇼핑몰입니다😎

      - title: ROCK-SCISSORS-PAPER
        link: https://github.com/gimpo5975/ROCK-SCISSORS-PAPER.git
        sub_title: ROCK-SCISSORS-PAPER 접속하기👈
        
        description: | # this will include new lines to allow paragraphs
        <mark>HTML</mark>,<mark>CSS</mark>,<mark>JavaScript</mark>를 이용한 간단한 가위바위보 게임입니다.🤡🤡

  - title: 직무경험 # Title for the section
    layout: list # Layout for the section
    content:
      - layout: left
        title: 말표산업
        sub_title: 생산관리
        caption: 2022.10~2022.12
        description: | # this will include new lines to allow paragraphs
          졸업학기에 직무경험을 해보고싶어서 취업계로 말표산업에 생산관리 직무로 근무했습니다.
         근무기간동안 광택제, 구두약 등 제품들을 생산하는 과정속에서 인력관리 제품 생산기한 조정 등 짧은 기간에 다양한 경험을 할 수 있었습니다.

      # - title: Convert Jenkins Build
      #   sub_title: Using MultiBranch Pipeline(Docker)
      #   caption: 2022.10 ~ 2022.11
      #   description: | # this will include new lines to allow paragraphs
      #     기존의 Jenkins는 동시에 빌드할 수 있는 숫자가 최대 3개였기에 빌드 속도가 느려지는 문제가 있었습니다. 해당 부분을 개선하고자 기존에 사용하던 Jenkins를 Docker를 이용한 Multi-Branch Pipeline으로 전환하였습니다.
      # - title: Test Automation
      #   sub_title: 테이블 자동삭제 및 증적자료 저장 기능 개발
      #   caption: 2022.09 ~ 2022.10
      #   description: | # this will include new lines to allow paragraphs
      #     기존에는 대량의 데이터를 저장하고 있었기 때문에 서비스의 성능에 영향을 미쳐 DBA분과 협업하여 수동 삭제로 진행하던 테이블 삭제를 자동으로 진행할 수 있도록 개발하였습니다.
      #     또한, 테이블 삭제 시 증적자료를 저장할 수 있도록 개발하였습니다. 반복했던 작업을 자동화하여 담당자의 생산성을 높일 수 있었습니다.
      # - title: Improving Nginx
      #   sub_title: Nginx를 이용한 서비스 품질 개선
      #   caption: 2022.06. ~ 2022.08
      #   description: | # this will include new lines to allow paragraphs
      #     기존 nginx를 개선하여 다음의 문제들을 해결하였습니다.
      #     - nginx exporter 설정을 통한 prometheus 메트릭 수집기능 개선
      #     - Reverse Proxy 설정을 통한 서비스의 보안성 개선
      #     - 미사용중인 HTTP METHOD Blocking을 통한 보안성 개선
      #     - nginx의 access_log 분리를 통한 로그 관리 개선
      # - title: Condition Checker Autoconfiguration
      #   sub_title: Autoconfiguration을 이용한 starter 개발
      #   caption: 2022.04. ~ 2022.07
      #   description: | # this will include new lines to allow paragraphs
      #     외부시스템 연결 상태를 확인하는 사내 오픈소스 `Condition Checker`의 Autoconfiguration 기능을 개발하였습니다.
      #     Autoconfiguration 기능을 통해 (Mysql, Mongodb, Redis, Rabbitmq)에 대한 연결상태를 dependency 등록만으로도 상태 체크를 할 수 있도록 개선하였습니다.
      # - title: LG Uplus Ucube System
      #   sub_title: 단말기 판매 기능 개발
      #   caption: 2021.06. ~ 2022.01
      #   description: | # this will include new lines to allow paragraphs
      #     통신사 신규가입 인원을 대상으로 단말기를 판매하는 기능을 개발하였습니다. 메인 기능에 대한 개발을 진행했으며 Sequence Diagram 및 테스트 코드를 작성하였습니다.
      #     모든 업무가 끝난 뒤 중복되는 로직 및 가독성이 떨어지는 코드를 리팩토링하여 코드의 가독성을 높였습니다.`
      
## Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
